name: Micropep
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - stringtie>=2.1.4
  - pyranges>=0.0.85
  - numpy>=1.19.2
  - biopython>=1.78
  - blast>=2.10.0
  - python=3.6
  - pandas>=1.1.2

